version: "3"
services:
  webapp:
    container_name: webapp
    # build: your_Dockerfile_folder
    # image: your_image
    # expose:
    #  - 5000
  zap:
    container_name: zap
    image: "owasp/zap2docker-bare"
    command: zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=123456
    expose:
      - 8080
    links:
      - webapp
  scan:
    container_name: scan
    image: "jscdroiddev/owasp-scan:latest"
    volumes:
      - ./reports:/opt/owasp/reports/
    environment:
      - APPSERVERNAME=webapp
      - APPPORT=5000
      - ZAPSERVERNAME=zap
      - ZAPAPIKEY=123456